### PR TITLE
V2.0 to main

### PR DESCRIPTION
**Pull request by vinayvis821**
Made it so the apply planet is the only planet that rotates

### CODE REVIEW

**Comment by jackheuberger** [comment]
Wait why are there so many file changes? Did you pull main before creating the pr?

**Comment by vinayvis821** [comment]
Yes, I forgot to pull main rip. I published the 2.0 branch. Nothing has changed except for the apply planet move on hover.

**Comment by jackheuberger** [comment]
I would abandon the PR, pull main, remake the change (via git stash or something else), and the recreate it

**Comment by vinayvis821** [comment]
Bad PR

**Pull request closed without merging**
